export const FETCH_MAIN_DATA ='FETCH_MAIN_DATA';
export const FETCH_EVENT_DETAILS = 'FETCH_EVENT_DETAILS';
export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST';
export const INSERT_BOARD = 'INSERT_BOARD';
export const FETCH_BOARD_DETAILS = 'FETCH_BOARD_DETAILS';
export const FETCH_EVENT_LIST = 'FETCH_EVENT_LIST';
export const FETCH_EVENT_DETAIL = 'FETCH_EVENT_DETAIL';